name: Build and Deploy APK
'on':
  workflow_run:
    workflows:
      - Android CI
    types:
      - completed
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: adopt
      - name: Set Executable Permission for gradlew
        run: |
          chmod +x ./gradlew
      - name: Build Android APK
        run: ./gradlew assembleDebug
      - name: Create testBuilds Folder
        run: mkdir -p testBuilds
      - name: Rename APK
        run: >-
          mv app/build/outputs/apk/debug/app-debug.apk
          "testBuilds/demo-\$DATETIME.apk"
      - name: Configure Git
        run: |
          git config --local user.email "Kumararun2002@yahoo.com"
          git config --local user.name "Your Name"
      - name: Commit and Push Changes
        run: |
          git add testBuilds/*
          git commit -m "Add debug APK"
          git push https://github.com/ArunPerkash/ASDT_3/ HEAD:main
        env:
          GITHUB_TOKEN: '${{ secrets.PAT_TOKEN }}'
